server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/test?useSSL=false&characterEncoding=utf-8
    username: root
    password:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
application.message: Hello Phil

mybatis:
 mapper-locations: classpath:mapping/*.xml
 type-aliases-package: com.example.demo.po

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
rabbitmq:
  host: 127.0.0.1
  port: 15672
  publisher-confirms: true #支持发布确认
  publisher-returns: true
server.jsp-servlet.init-parameters.development: true
